name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -H -p 22278 165.101.248.107 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh hashim@165.101.248.107 -p 22278 << 'EOF'
            set -e
            cd /opt/logistics/www
            git pull origin main
            docker compose --env-file deploy.env up -d --build
          EOF
